DATABASE_URL="postgresql://<USER>:<PASS>@<HOST>:<PORT>/<DB>?sslmode=require"
STRAVA_CLIENT_ID="<your_strava_app_id>"
STRAVA_CLIENT_SECRET="<your_strava_app_secret>"
STRAVA_REDIRECT_URI="https://<your-streamlit-app>.streamlit.app"
